### ISSUE TITLE
Can't find or create one ai instance with setting appInsightsInstance's name when use 'azure_auth_maven_plugin' auth type

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-maven-plugins#1078]
### Plugin name and version
azure-functions-maven-plugin 1.4.2-SNAPSHOT
### Plugin configuration in your `pom.xml`
```
 <configuration>
 <authType>azure_auth_maven_plugin</authType>
 <subscriptionId>XXXXXXXXXX</subscriptionId>
 <appName>${functionAppName}</appName>
 <resourceGroup>chyl0601rg</resourceGroup>
 <appServicePlanName>java-functions-app-service-plan</appServicePlanName>
 <region>westus</region>
 <runtime>
 <os>windows</os>
 </runtime>
 <appInsightsInstance>chylai</appInsightsInstance>
 <appSettings>
 <property>
 <name>FUNCTIONS_EXTENSION_VERSION</name>
 <value>~3</value>
 </property>
 </appSettings>
 </configuration>
```
### Actual behavior
![image](https://user-images.githubusercontent.com/41051257/83402737-e036cb80-a439-11ea-99fe-a55c62319419.png)

```
[ERROR] Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:1.4.2-SNAPSHOT:deploy (default-cli) on project 
chyl0601: Parameter this.client.subscriptionId() is required and cannot be null. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:1.4.2-SNAPSHOT:deploy (default-cli) on project chyl0601: Parameter this.client.subscriptionId() is required and cannot be null.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Parameter this.client.subscriptionId() is required and cannot be null.
        at com.microsoft.azure.maven.AbstractAzureMojo.handleException(AbstractAzureMojo.java:509)
        at com.microsoft.azure.maven.AbstractAzureMojo.execute(AbstractAzureMojo.java:443)
        at com.microsoft.azure.maven.function.AbstractFunctionMojo.execute(AbstractFunctionMojo.java:183)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.IllegalArgumentException: Parameter this.client.subscriptionId() is required and cannot be null.
        at com.microsoft.azure.management.applicationinsights.v2015_05_01.implementation.ComponentsInner.getByResourceGroupWithServiceResponseAsync(ComponentsInner.java:479)
        at com.microsoft.azure.management.applicationinsights.v2015_05_01.implementation.ComponentsInner.getByResourceGroupAsync(ComponentsInner.java:458)
        at com.microsoft.azure.management.applicationinsights.v2015_05_01.implementation.ComponentsImpl.getInnerAsync(ComponentsImpl.java:37)
        at com.microsoft.azure.arm.resources.collection.implementation.GroupableResourcesCoreImpl.getByResourceGroupAsync(GroupableResourcesCoreImpl.java:115)
        at com.microsoft.azure.arm.resources.collection.implementation.GroupableResourcesCoreImpl.getByResourceGroup(GroupableResourcesCoreImpl.java:110)
        at com.microsoft.azure.arm.resources.collection.implementation.GroupableResourcesCoreImpl.getByResourceGroup(GroupableResourcesCoreImpl.java:34)
        at com.microsoft.azure.common.applicationinsights.ApplicationInsightsManager.getApplicationInsightInstance(ApplicationInsightsManager.java:33)
        at com.microsoft.azure.maven.function.DeployMojo.getApplicationInsights(DeployMojo.java:213)
        at com.microsoft.azure.maven.function.DeployMojo.getOrCreateApplicationInsights(DeployMojo.java:207)
        at com.microsoft.azure.maven.function.DeployMojo.buildApplicationInsightConnection(DeployMojo.java:191)
        at com.microsoft.azure.maven.function.DeployMojo.createFunctionApp(DeployMojo.java:136)
        at com.microsoft.azure.maven.function.DeployMojo.createOrUpdateFunctionApp(DeployMojo.java:126)
        at com.microsoft.azure.maven.function.DeployMojo.doExecute(DeployMojo.java:99)
        at com.microsoft.azure.maven.AbstractAzureMojo.execute(AbstractAzureMojo.java:438)
        ... 23 more
```

**Comment by ZhengJun003** [comment]
Test Pass
