### ISSUE TITLE
CloudException: OnError while emitting onNext value: retrofit2.Response.class

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-maven-plugins#1130]
### Plugin name and version
azure-spring-cloud-maven-plugin:1.3.0-SNAPSHOT
### Plugin configuration in your `pom.xml`
```
            <configuration>
                <subscriptionId>xxxxxx</subscriptionId>
                <clusterName>harryspring</clusterName>
                <appName>harrypet01</appName>
                <isPublic>true</isPublic>
                <deployment>
                    <cpu>1</cpu>
                    <memoryInGB>1</memoryInGB>
                    <instanceCount>1</instanceCount>
                    <runtimeVersion>Java 8</runtimeVersion>
                    <resources>
                        <resource>
                            <filtering/>
                            <mergeId/>
                            <targetPath/>
                            <directory>${project.basedir}/target</directory>
                            <includes>
                                <include>*.jar</include>
                            </includes>
                        </resource>
                    </resources>
                </deployment>
            </configuration>
```

### Actual behavior
```
[INFO] x-ms-client-request-id: 5c9823b8-5fec-493f-b0a1-386aa9e5330f
[INFO] 273-byte body:
{"properties":{"source":{"type":"Jar","relativePath":"resources/3da6560d9d868f523ca78ee35a0aa54bf21bd51dbad24fceeac257eb982f4eea-2020082402-e0d6fd4b-f650-40dd-9e5d-250d3acc13b7"},"deploymentSettings":{"cpu":1,"memoryInGB":1,"runtimeVersion":"Java_8"}},"sku":{"capacity":1}}
[INFO] --> END PUT
[INFO] <-- 400  https://management.azure.com/subscriptions/xxxxxxx/resourceGroups/harrytest/providers/Microsoft.AppPlatform/Spring/harryspring/apps/harrypet01/deployments/default?api-version=2020-07-01 (277 ms, 270-byte body)
[INFO] cache-control: no-cache
[INFO] content-length: 270
[INFO] content-type: application/json; charset=utf-8
[INFO] date: Mon, 24 Aug 2020 02:26:45 GMT
[INFO] expires: -1
[INFO] pragma: no-cache
[INFO] server: nginx/1.17.7
[INFO] strict-transport-security: max-age=31536000; includeSubDomains
[INFO] x-content-type-options: nosniff
[INFO] x-ms-client-request-id: 5c9823b8-5fec-493f-b0a1-386aa9e5330f
[INFO] x-ms-correlation-request-id: 31d2d692-a1d2-4064-bd64-48048f7c1a03
[INFO] x-ms-ratelimit-remaining-subscription-resource-requests: 1199
[INFO] x-ms-request-id: 31d2d692-a1d2-4064-bd64-48048f7c1a03
[INFO] x-ms-routing-request-id: WESTUS:20200824T022645Z:31d2d692-a1d2-4064-bd64-48048f7c1a03        
[INFO] x-rp-server-mvid: d8cff8a2-0549-4ee1-8c3d-fa9d1b5306d8
[INFO] 270-byte body:
{"errors":{"Sku.Name":["The property 'Name' is required."],"Sku.Tier":["The property 'Tier' is required."]},"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"|f241cf3d-4da70331ca6bdd21."}
[INFO] <-- END HTTP
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 50.810 s
[INFO] Finished at: 2020-08-24T02:26:45+00:00
[INFO] Final Memory: 40M/140M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.microsoft.azure:azure-spring-cloud-maven-plugin:1.3.0-SNAPSHOT:deploy (default-cli) on project spring-petclinic: null: MojoFailureException: CloudException: OnError 
while emitting onNext value: retrofit2.Response.class -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.microsoft.azure:azure-spring-cloud-maven-plugin:1.3.0-SNAPSHOT:deploy (default-cli) on project spring-petclinic: null        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)      
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)    
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException
        at com.microsoft.azure.maven.spring.AbstractSpringMojo.execute(AbstractSpringMojo.java:137) 
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: com.microsoft.azure.CloudException
        at com.microsoft.azure.AzureClient.createExceptionFromResponse(AzureClient.java:771)        
        at com.microsoft.azure.AzureClient.access$100(AzureClient.java:33)
        at com.microsoft.azure.AzureClient$3.call(AzureClient.java:160)
        at com.microsoft.azure.AzureClient$3.call(AzureClient.java:157)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)        
        at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)
        at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
        at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)     
        at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)     
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:81)
        at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:27)
        at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:39)
        at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:27)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153)
        at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32)        
        at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22)        
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153)
        at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32)        
        at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22)        
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:10423)
        at rx.Observable.subscribe(Observable.java:10390)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443)
        at rx.observables.BlockingObservable.last(BlockingObservable.java:226)
        at com.microsoft.azure.management.appplatform.v2020_07_01.implementation.DeploymentsInner.createOrUpdate(DeploymentsInner.java:254)
        at com.microsoft.azure.maven.spring.spring.SpringDeploymentClient.createDeployment(SpringDeploymentClient.java:119)
        at com.microsoft.azure.maven.spring.spring.SpringDeploymentClient.createOrUpdateDeployment(SpringDeploymentClient.java:82)
        at com.microsoft.azure.maven.spring.DeployMojo.doExecute(DeployMojo.java:117)
        at com.microsoft.azure.maven.spring.AbstractSpringMojo.execute(AbstractSpringMojo.java:133) 
        ... 22 more
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: retrofit2.Response.class
        at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)        
        ... 63 more
```

### Steps to reproduce the problem

1. Install https://github.com/microsoft/azure-maven-plugins/tree/github-issue-1125
2. git clone https://github.com/xscript/PiggyMetrics
3. execute cd PiggyMetrics and mvn clean package -DskipTests
4. execute mvn com.microsoft.azure:azure-spring-cloud-maven-plugin:1.3.0-SNAPSHOT:config
5. execute mvn azure-spring-cloud:deploy

**Comment by ZhengJun003** [comment]
Test the branch: github-issue-1125, this issue is fixed, so close it

**Comment by wangmingliang-ms** [comment]
https://github.com/microsoft/azure-maven-plugins/pull/1126/commits/5cb2a9da22a763f7d1cbb37618a865b538e5df9a
https://github.com/microsoft/azure-maven-plugins/pull/1126/commits/342cdfb0039566cdb519f540e5dd4841807ecf1f

**Comment by ZhengJun003** [comment]
jvmOptions.invalidLetters '-Xmx500m -Xmx100m'

![image](https://user-images.githubusercontent.com/41051257/92195993-cecde700-eea0-11ea-80d0-8978cc287c3b.png)

**Comment by ZhengJun003** [comment]
Test in the branch: github-issue-1125, this issue is fixed, so close it
