### ISSUE TITLE
Deploy function app failed with linux runtime sometimes

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-maven-plugins#1248]
### Plugin name and version

- OS: Win/Mac
- Plugin: Azure-functions-maven-plugin 1.9.1

### Plugin configuration in your `pom.xml`
```
              <configuration>
                    <appName>${functionAppName}</appName>
                    <resourceGroup>harryfunc08</resourceGroup>
                    <region>eastus</region>
                    <deploymentType>RUN_FROM_BLOB</deploymentType>
                    <runtime>
                        <os>linux</os>
                        <javaVersion>11</javaVersion>
                    </runtime>
                    <appSettings>
                        <property>
                            <name>FUNCTIONS_EXTENSION_VERSION</name>
                            <value>~3</value>
                        </property>
                    </appSettings>
                </configuration>
```

### Actual behavior
```
[ERROR] Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:1.9.1:deploy (default-cli) on project harryfunc: Status code 400, {"Code":"BadRequest","Message":"Encountered an error (InternalServerError) from host runtime.","Target":null,"Details":[{"Message":"Encountered an error (InternalServerError) from host runtime."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","Message":"Encountered an error (InternalServerError) from host runtime."}}],"Innererror":null} -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:1.9.1:deploy (default-cli) on project harryfunc: Status code 400, {"Code":"BadRequest","Message":"Encountered an error (InternalServerError) from host runtime.","Target":null,"Details":[{"Message":"Encountered an error (InternalServerError) 
from host runtime."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","Message":"Encountered an error (InternalServerError) from host runtime."}}],"Innererror":null}
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)        
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Status code 400, {"Code":"BadRequest","Message":"Encountered an 
error (InternalServerError) from host runtime.","Target":null,"Details":[{"Message":"Encountered an error (InternalServerError) from host runtime."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","Message":"Encountered an error (InternalServerError) from host runtime."}}],"Innererror":null}
        at com.microsoft.azure.maven.AbstractAzureMojo.handleException(AbstractAzureMojo.java:537)
        at com.microsoft.azure.maven.AbstractAzureMojo.execute(AbstractAzureMojo.java:471)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: com.microsoft.azure.common.exceptions.AzureExecutionException: Status code 400, {"Code":"BadRequest","Message":"Encountered an error (InternalServerError) from host runtime.","Target":null,"Details":[{"Message":"Encountered an error (InternalServerError) from host runtime."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","Message":"Encountered an error (InternalServerError) from host runtime."}}],"Innererror":null}
        at com.microsoft.azure.maven.AbstractAzureMojo.executeWithTimeRecorder(AbstractAzureMojo.java:548)
        at com.microsoft.azure.maven.function.DeployMojo.deployArtifact(DeployMojo.java:160)
        at com.microsoft.azure.maven.function.DeployMojo.doExecute(DeployMojo.java:147)
        at com.microsoft.azure.maven.AbstractAzureMojo.execute(AbstractAzureMojo.java:466)
        ... 22 more
Caused by: com.microsoft.azure.management.appservice.DefaultErrorResponseException: Status code 400, {"Code":"BadRequest","Message":"Encountered an error (InternalServerError) from host runtime.","Target":null,"Details":[{"Message":"Encountered an error (InternalServerError) from host runtime."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","Message":"Encountered an error (InternalServerError) from host runtime."}}],"Innererror":null}
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122)
        at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
        at com.microsoft.azure.management.appservice.implementation.WebAppsInner.syncFunctionTriggersDelegate(WebAppsInner.java:41457)
        at com.microsoft.azure.management.appservice.implementation.WebAppsInner.access$32900(WebAppsInner.java:60)        
        at com.microsoft.azure.management.appservice.implementation.WebAppsInner$1399.call(WebAppsInner.java:41443)        
        at com.microsoft.azure.management.appservice.implementation.WebAppsInner$1399.call(WebAppsInner.java:41439)        
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
        at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)
        at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
        at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
        at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.Completable$10.call(Completable.java:588)
        at rx.Completable$10.call(Completable.java:567)
        at rx.Completable.unsafeSubscribe(Completable.java:2035)
        at rx.Completable$26.call(Completable.java:1730)
        at rx.Completable$26.call(Completable.java:1725)
        at rx.Completable.unsafeSubscribe(Completable.java:2035)
        at rx.Completable.unsafeSubscribe(Completable.java:2083)
        at rx.Completable.unsafeSubscribe(Completable.java:2067)
        at rx.Completable$32.call(Completable.java:2253)
        at rx.Completable$32.call(Completable.java:2250)
        at rx.Observable.subscribe(Observable.java:10423)
        at rx.Observable.subscribe(Observable.java:10390)
        at rx.observables.BlockingObservable.subscribe(BlockingObservable.java:477)
        at com.microsoft.azure.management.appservice.implementation.FunctionAppImpl.syncTriggers(FunctionAppImpl.java:527) 
        at com.microsoft.azure.common.function.handlers.artifact.RunFromBlobArtifactHandlerImpl.publish(RunFromBlobArtifactHandlerImpl.java:55)
        at com.microsoft.azure.maven.function.DeployMojo.lambda$deployArtifact$0(DeployMojo.java:160)
        at com.microsoft.azure.maven.AbstractAzureMojo.executeWithTimeRecorder(AbstractAzureMojo.java:546)
        ... 25 more
```

**Comment by ZhengJun003** [comment]
Test in bits commicrosoftazure-4465, this issue is fixed.
