### ISSUE TITLE
Hidden NullPointerException and failed deployment with ftp to linux with jre8

### ISSUE THREAD

**Issue by freeone3000** [Microsoft/azure-maven-plugins#385]
### Plugin name and version
com.microsoft.azure:azure-webapp-maven-plugin:1.2.0

### Plugin configuration in your `pom.xml`
            <plugin>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure-webapp-maven-plugin</artifactId>
                <version>1.2.0</version>
                <configuration>
                    <resourceGroup>production</resourceGroup>
                    <appName>feedbackservice</appName>
                    <linuxRuntime>jre8</linuxRuntime>
                    <deploymentType>ftp</deploymentType>
                    <resources>
                        <resource>
                            <directory>${project.basedir}/target</directory>
                            <includes>
                                <include>*.jar</include>
                            </includes>
                            <excludes>
                                <exclude>*.class</exclude>
                            </excludes>
                        </resource>
                    </resources>
                </configuration>
            </plugin>

### Expected behavior
The artifact should be deployed.

### Actual behavior
Silent crash, with hidden NullPointerException revealed with -e.

Stacktrace follows:
    james@james-HP-Z8-G4-Workstation:~/Code/MRCFeedbackCollection$ /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -Dmaven.multiModuleProjectDirectory=/home/james/Code/MRCFeedbackCollection -Dmaven.home=/home/james/idea-IU-182.4323.46/plugins/maven/lib/maven3 -Dclassworlds.conf=/home/james/idea-IU-182.4323.46/plugins/maven/lib/maven3/bin/m2.conf -javaagent:/home/james/idea-IU-182.4323.46/lib/idea_rt.jar=35397:/home/james/idea-IU-182.4323.46/bin -Dfile.encoding=UTF-8 -classpath /home/james/idea-IU-182.4323.46/plugins/maven/lib/maven3/boot/plexus-classworlds-2.5.2.jar org.codehaus.classworlds.Launcher -Didea.version=2018.2.3 com.microsoft.azure:azure-webapp-maven-plugin:1.2.0:deploy
    [INFO] Scanning for projects...
    [INFO]                                                                         
    [INFO] ------------------------------------------------------------------------
    [INFO] Building mrc-feedback-collection 1.0-SNAPSHOT
    [INFO] ------------------------------------------------------------------------
    [INFO] 
    [INFO] --- azure-webapp-maven-plugin:1.2.0:deploy (default-cli) @ mrc-feedback-collection ---
    [INFO] Start deploying to Web App mrcfeedbackservice...
    [INFO] Authenticate with Azure CLI 2.0
    [INFO] Updating target Web App...
    [INFO] Successfully updated Web App.
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 7.007 s
    [INFO] Finished at: 2018-09-11T17:19:56-04:00
    [INFO] Final Memory: 64M/2253M
    [INFO] ------------------------------------------------------------------------
    [WARNING] The requested profile "nexus" could not be activated because it does not exist.
    [ERROR] Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:1.2.0:deploy (default-cli) on project mrc-feedback-collection: java.lang.NullPointerException -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
    james@james-HP-Z8-G4-Workstation:~/Code/MRCFeedbackCollection$ /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -Dmaven.multiModuleProjectDirectory=/home/james/Code/MRCFeedbackCollection -Dmaven.home=/home/james/idea-IU-182.4323.46/plugins/maven/lib/maven3 -Dclassworlds.conf=/home/james/idea-IU-182.4323.46/plugins/maven/lib/maven3/bin/m2.conf -javaagent:/home/james/idea-IU-182.4323.46/lib/idea_rt.jar=35397:/home/james/idea-IU-182.4323.46/bin -Dfile.encoding=UTF-8 -classpath /home/james/idea-IU-182.4323.46/plugins/maven/lib/maven3/boot/plexus-classworlds-2.5.2.jar org.codehaus.classworlds.Launcher -Didea.version=2018.2.3 com.microsoft.azure:azure-webapp-maven-plugin:1.2.0:deploy -e
    [INFO] Error stacktraces are turned on.
    [INFO] Scanning for projects...
    [INFO]                                                                         
    [INFO] ------------------------------------------------------------------------
    [INFO] Building mrc-feedback-collection 1.0-SNAPSHOT
    [INFO] ------------------------------------------------------------------------
    [INFO] 
    [INFO] --- azure-webapp-maven-plugin:1.2.0:deploy (default-cli) @ mrc-feedback-collection ---
    [INFO] Start deploying to Web App mrcfeedbackservice...
    [INFO] Authenticate with Azure CLI 2.0
    [INFO] Updating target Web App...
    [INFO] Successfully updated Web App.
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 6.925 s
    [INFO] Finished at: 2018-09-11T17:20:28-04:00
    [INFO] Final Memory: 64M/2239M
    [INFO] ------------------------------------------------------------------------
    [WARNING] The requested profile "nexus" could not be activated because it does not exist.
    [ERROR] Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:1.2.0:deploy (default-cli) on project mrc-feedback-collection: java.lang.NullPointerException -> [Help 1]
    org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:1.2.0:deploy (default-cli) on project mrc-feedback-collection: java.lang.NullPointerException
            at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
            at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
            at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
            at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
            at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
            at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
            at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
            at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
            at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
            at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
            at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
            at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
            at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
            at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
            at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
            at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
            at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
    Caused by: org.apache.maven.plugin.MojoExecutionException: java.lang.NullPointerException
            at com.microsoft.azure.maven.AbstractAzureMojo.handleException(AbstractAzureMojo.java:346)
            at com.microsoft.azure.maven.AbstractAzureMojo.execute(AbstractAzureMojo.java:292)
            at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
            at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
            ... 21 more
    Caused by: java.lang.NullPointerException
            at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:273)
            at java.nio.file.Paths.get(Paths.java:84)
            at com.microsoft.azure.maven.Utils.copyResources(Utils.java:85)
            at com.microsoft.azure.maven.webapp.handlers.FTPArtifactHandlerImpl.copyResourcesToStageDirectory(FTPArtifactHandlerImpl.java:42)
            at com.microsoft.azure.maven.webapp.handlers.FTPArtifactHandlerImpl.publish(FTPArtifactHandlerImpl.java:37)
            at com.microsoft.azure.maven.webapp.DeployMojo.deployArtifacts(DeployMojo.java:78)
            at com.microsoft.azure.maven.webapp.DeployMojo.doExecute(DeployMojo.java:41)
            at com.microsoft.azure.maven.AbstractAzureMojo.execute(AbstractAzureMojo.java:287)
            ... 23 more
    [ERROR] 
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException\

### Steps to reproduce the problem
Create a webapp.
Log in with az login.
Create a new maven project with the above webapp configuration.
Run.

**Comment by SummerSun** [comment]
@freeone3000 
Thank you for reporting this to us. We are investigating the issue.

By the way, we have released `1.4.0` of the plugin `azure-webapp-maven-plugin`. To unblock your work, you could try to upgrade to the latest version and give it a try again.

**Comment by freeone3000** [comment]
Yes, this was solved by updating to 1.4.0, instead of the version listed in the documentation. Thanks.
