### ISSUE TITLE
Functions maven plugin doesn't check the java version right way for java version used in function cli

### ISSUE THREAD

**Issue by andxu** [microsoft/azure-maven-plugins#983]
When I have java.exe(1.8)  in Path, while have JAVA_HOME=jdk11, I will meet the error(which doesn't address the right reason too) 

```
[1/7/2020 6:16:28 AM] Executed 'Functions.HttpTrigger-Java' (Failed, Id=3023920c-e2d7-4aa0-8410-e2fd4f65c5c7)
[1/7/2020 6:16:28 AM] System.Private.CoreLib: Exception while executing function: Functions.HttpTrigger-Java. System.Private.CoreLib: Result: Failure
Exception: ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
Stack: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
[1/7/2020 6:16:28 AM]   at com.microsoft.azure.functions.worker.reflect.DefaultClassLoaderProvider.addUrlToSystemClassLoader(DefaultClassLoaderProvider.java:72)
[1/7/2020 6:16:28 AM]   at com.microsoft.azure.functions.worker.reflect.DefaultClassLoaderProvider.addUrl(DefaultClassLoaderProvider.java:62)
[1/7/2020 6:16:28 AM]   at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.addSearchPathsToClassLoader(JavaFunctionBroker.java:64)
[1/7/2020 6:16:28 AM]   at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.loadMethod(JavaFunctionBroker.java:33)
[1/7/2020 6:16:28 AM]   at com.microsoft.azure.functions.worker.handler.FunctionLoadRequestHandler.execute(FunctionLoadRequestHandler.java:27)
[1/7/2020 6:16:28 AM]   at com.microsoft.azure.functions.worker.handler.FunctionLoadRequestHandler.execute(FunctionLoadRequestHandler.java:9)
[1/7/2020 6:16:28 AM]   at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[1/7/2020 6:16:28 AM]   at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
[1/7/2020 6:16:28 AM]   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[1/7/2020 6:16:28 AM]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[1/7/2020 6:16:28 AM]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[1/7/2020 6:16:28 AM]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[1/7/2020 6:16:28 AM]   at java.base/java.lang.Thread.run(Thread.java:830)
[1/7/2020 6:16:28 AM] .
```

**Comment by andxu** [comment]
Dup as https://github.com/microsoft/azure-maven-plugins/issues/983
